import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    background: {
        flex: 1,
        backgroundColor: '#2194BF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    Logo: {
        alignSelf: 'center',
        resizeMode: 'cover',
        width: 120,
        height: 120,
        marginVertical: 30,
        justifyContent: "center",
        borderRadius: 60,
    },
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        marginBottom: '5%',
    },
    input: {
        backgroundColor: '#FFF',
        width: '90%',
        marginBottom: 4,
        color: '#191919',
        fontSize: 17,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: "#161925",
        padding: 5,
        marginBottom: '5%',
    },
    inputNum: {
        backgroundColor: '#FFF',
        width: '19%',
        marginBottom: 4,
        color: '#191919',
        fontSize: 17,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: "#161925",
        padding: 5,
        marginRight: '1%',
        marginBottom: '5%',
    },
    inputComplemento: {
        backgroundColor: '#FFF',
        width: '69%',
        marginBottom: 4,
        color: '#191919',
        fontSize: 17,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: "#161925",
        padding: 5,
        marginBottom: '5%',
    },
    numeroComplemento: {
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    submitBtn: {
        backgroundColor: '#161925',
        width: '30%',
        borderRadius: 10,
        padding: 10,
        alignItems: 'center',
        justifyContent: 'center',
        color: '#FFF',
    },
    submitText: {
        color: '#CBF7ED',
        fontSize: 17,
    },
    touchable: {
        height: 120,
        width: 120,
        alignItems: 'center',
        justifyContent: 'center',
      },
});