import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    background: {
        flex: 1,
        backgroundColor: '#8DD7CF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    Logo: {
        alignSelf: 'center',
        resizeMode: 'cover',
        width: 120,
        height: 120,
        marginVertical: '7%',
        borderRadius: 180,
    },
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        width: '90%',
        marginBottom: '5%',
    },
    input: {
        backgroundColor: '#FFF',
        width: '90%',
        marginBottom: 4,
        color: '#191919',
        fontSize: 17,
        borderRadius: 10,
        padding: 5,
        marginBottom: '5%',
    },
    inputNum: {
        backgroundColor: '#FFF',
        width: '19%',
        marginBottom: 4,
        color: '#191919',
        fontSize: 17,
        borderRadius: 10,
        padding: 5,
        marginRight: '1%',
        marginBottom: '5%',
    },
    inputComplemento: {
        backgroundColor: '#FFF',
        width: '69%',
        marginBottom: 4,
        color: '#191919',
        fontSize: 17,
        borderRadius: 10,
        padding: 5,
        marginBottom: '5%',
    },
    numeroComplemento: {
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    submitBtn: {
        backgroundColor: '#836FFF',
        width: '30%',
        borderRadius: 5,
        padding: 5,
        alignItems: 'center',
        justifyContent: 'center',
        color: '#FFF',
    },
    submitText: {
        color: '#FFF',
        fontSize: 17,
    },
});